# Site Author
author:
  name             : "Wanyun Zhou"
  avatar           : "/images/wanyunzh.png"
  email            : "wzhou266@connect.hkust-gz.edu.cn"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:wzhou266@connect.hkust-gz.edu.cn"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wanyunzh"
